spring:
  application:
    name: WeSparrow
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:postgresql://localhost:5432/cardgame
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.orm.jdbc.bind: info
